In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,3,4,2,9])
arr

array([1, 3, 4, 2, 9])

In [3]:
type(arr)

numpy.ndarray

In [4]:
size =  1000000
python_list = list(range(size))
start = time.time()
sq_array = [x**2 for x in python_list]
end = time.time()
print({end - start})


{0.16879534721374512}


In [5]:
np_array = np.array(python_list)
start = time.time()
sq_array  = np_array ** 2
end = time.time()
print({end - start})

{0.016995668411254883}


In [6]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1 , type(arr1) , arr1.shape)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2 , type(arr2) , arr2.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [7]:
arr1 = np.zeros((2,3) , dtype = "int64")
arr1

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [8]:
arr2 = np.ones((5,), dtype = "int64")
arr2

array([1, 1, 1, 1, 1], dtype=int64)

In [9]:
arr3 = np.eye((3), dtype = "int64")
arr3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [10]:
arr4 = np.linspace(1,100,3) 
arr4

array([  1. ,  50.5, 100. ])

In [11]:
arr5 = np.full((2,3),100)
arr5

array([[100, 100, 100],
       [100, 100, 100]])

In [12]:
arr6 = np.arange(0 , 11 , 3)
arr6

array([0, 3, 6, 9])

In [13]:
arr7 = np.array([1,3,2,4,5,6,7])

print(arr7.shape)
print(arr7.size)
print(arr7.dtype)
print(arr7.ndim)

float_list = arr.astype(np.float64)
print(type(float_list))

(7,)
7
int32
1
<class 'numpy.ndarray'>


In [14]:
arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]  , [10,11,12]])
print(np.shape(arr8))

(4, 3)


In [15]:
reshaped_array = arr8.reshape((3,4))

In [16]:
reshaped_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
flatten = arr8.flatten()

In [18]:
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
arr9 = np.array([1,2,3,4,5,6,7,8,9])
print(arr9[0])

1


In [20]:
#  fancy indexing
idx = [0,1,2] 
print(arr9[idx])

[1 2 3]


In [21]:
# boolean indexing
print(arr9[arr9>5])

[6 7 8 9]


In [22]:
print(arr9[arr9 %2 == 0])

[2 4 6 8]


In [23]:
print(arr9[1:])

[2 3 4 5 6 7 8 9]


In [24]:
print(arr9[1:5])

[2 3 4 5]


In [25]:
print(arr9[::8])

[1 9]


In [26]:
print(arr9[::])

[1 2 3 4 5 6 7 8 9]


In [27]:
arr2d = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr2d)

print(np.sum(arr2d))

sum_of_columns = np.sum(arr2d , axis = 0)
sum_of_columns

sum_of_rows = np.sum(arr2d , axis = 1)
sum_of_rows

print(arr2d[1:3 , 2:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[[6]
 [9]]


In [28]:
# 3d array

arr10 = np.array([[[1,2] , [3,4] ,[5,6]] , [[7,8] , [9,10] , [11 ,12]]])

In [29]:
arr10

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [30]:
arr10[0 , 1 , 1]

4

In [31]:
# vectorization and Broadcasting

In [32]:
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1 +5)

[ 6  7  8  9 10 11 12]


In [33]:
arr2 = np.array([[1,2,3,4,5,6,7] , [7,8 , 9 , 0 , 1 ,2,7]])

In [34]:
print(arr1 + arr2)

[[ 2  4  6  8 10 12 14]
 [ 8 10 12  4  6  8 14]]


In [35]:
arr11 = np.array([[1,2] , [3 , 4]])
mean = np.mean(arr11)
std_dev = np.std(arr11)

normalised_array = (arr11-mean)/std_dev
print(normalised_array)
print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [36]:
arr12 = np.array([1,2,4,5,6,7,8])
print(np.sum(arr12))
print(np.product(arr12))
print(np.min(arr12))
print(np.max(arr12))
print(np.argmin(arr12))
print(np.argmax(arr12))
print(np.mean(arr12))
print(np.std(arr12))
print(np.median(arr12))
print(np.var(arr12))


33
13440
1
8
0
6
4.714285714285714
2.3733211036908783
5.0
5.63265306122449


In [47]:
arr13 = np.array([1,2,3,5,6,7,8,9,10,0])
print(np.square(arr13))
print(np.sqrt(arr13))
print(np.log(arr13))
print(np.log2(arr13))
print(np.exp(arr13))
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.sort(arr13))


[  1   4   9  25  36  49  64  81 100   0]
[1.         1.41421356 1.73205081 2.23606798 2.44948974 2.64575131
 2.82842712 3.         3.16227766 0.        ]
[0.         0.69314718 1.09861229 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458 2.30258509       -inf]
[0.         1.         1.5849625  2.32192809 2.5849625  2.80735492
 3.         3.169925   3.32192809       -inf]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
 2.20264658e+04 1.00000000e+00]
3.0
4.0
3.0
[ 0  1  2  3  5  6  7  8  9 10]


C:\Users\HP\AppData\Local\Temp\ipykernel_29380\854278348.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr13))
C:\Users\HP\AppData\Local\Temp\ipykernel_29380\854278348.py:5: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(arr13))
